# Generated by Django 6.0.6 on 2026-08-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
